# Generated by Django 4.1.3 on 2023-07-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_ordermodel_time_of_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='time_of_order',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='time_of_purchase',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
